#pragma once
#define _CRT_SECURE_NO_WARNINGS

#include "Error.h"
#include "In.h"
#include "IT.h"
#include "Log.h"
#include "LT.h"
#include "Parm.h"
#include "GRB.h"
#include "LexAnalize.h"
#include "MFST.h"
#include "PolishNotation.h"
#include "OT.h"
#include "SemAnalize.h"
#include "CodeGeneration.h"

#include <cstdarg>
#include <ctime>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <string>
#include <Windows.h>
#include <locale>
#include <cwchar>
#include <tchar.h>
#include <stdarg.h>
#include <map>
